package com.lemon.team.electronics.util

import com.lemon.team.electronics.R

object CategoryMap {

    val categoryName = mapOf(
        CategoriesId.MIC to R.string.microphone,
        CategoriesId.ADAPTER to R.string.cable_and_adapter,
        CategoriesId.CASE to R.string._case,
        CategoriesId.TABLET to R.string.drawing_tablet,
        CategoriesId.CPU to R.string.cpu,
        CategoriesId.GRAPHICS_CARD to R.string.graphics_card,
        CategoriesId.LAPTOP_FAN to R.string.laptop_fan,
        CategoriesId.CASE_FAN to R.string.case_fan,
        CategoriesId.SIMULATORS to R.string.controllers_simulators,
        CategoriesId.HEADSETS to R.string.headset,
        CategoriesId.REPLACEMENT_EAR_PADS to R.string.replacement_ear_pads,
        CategoriesId.STORAGE_AND_MEMORY to R.string.storage_and_memory,
        CategoriesId.EXTERNAL_HARD to R.string.extrernal_hard,
        CategoriesId.GAMING_CHAIRS to R.string.gaming_chair_table,
        CategoriesId.LAPTOP to R.string.laptop,
        CategoriesId.WEBCAM to R.string.webcam,
        CategoriesId.MONITOR_STAND to R.string.monitor_stand,
        CategoriesId.POWER_PRODUCTS to R.string.power_products,
        CategoriesId.POWER_SUPPLY to R.string.power_supply,
        CategoriesId.FLASH_DRIVES to R.string.flash_drive,
        CategoriesId.MOUSE to R.string.mouse,
        CategoriesId.KEYBOARD to R.string.keyboard,
        CategoriesId.MOTHERBOARD to R.string.motherboard,
        CategoriesId.PAD_MOUSE to R.string.mouse_pad,
        CategoriesId.TABLET_AND_MOBILES to R.string.tablet_and_mobile,
        CategoriesId.MONITORS to R.string.monitor,
        CategoriesId.OTHER_ITEMS to R.string.other_items,
        CategoriesId.SOUND_DEVICE to R.string.sound_device,
        CategoriesId.SUGGESTED_COMPILATIONS to R.string.suggested_setup,
        CategoriesId.STREAM_TOOLS to R.string.stream_tools,
        CategoriesId.COOLERS to R.string.coolers,
        CategoriesId.PC_SPEAKER to R.string.pc_speakers,
    )

    val categoryIcon = mapOf(
        CategoriesId.MIC to R.drawable.ic_mic,
        CategoriesId.ADAPTER to R.drawable.ic_cable,
        CategoriesId.CASE to R.drawable.ic_case_icon,
        CategoriesId.TABLET to R.drawable.ic_ci_tablet,
        CategoriesId.CPU to R.drawable.ic_cpu,
        CategoriesId.GRAPHICS_CARD to R.drawable.ic_graphics_card,
        CategoriesId.LAPTOP_FAN to R.drawable.ic_fan,
        CategoriesId.CASE_FAN to R.drawable.ic_fan,
        CategoriesId.SIMULATORS to R.drawable.ic_game,
        CategoriesId.HEADSETS to R.drawable.ic_headphone,
        CategoriesId.REPLACEMENT_EAR_PADS to R.drawable.ic_headphone,
        CategoriesId.STORAGE_AND_MEMORY to R.drawable.ic_storage,
        CategoriesId.EXTERNAL_HARD to R.drawable.ic_storage,
        CategoriesId.GAMING_CHAIRS to R.drawable.ic_chairs,
        CategoriesId.LAPTOP to R.drawable.ic_laptop,
        CategoriesId.WEBCAM to R.drawable.ic_webcam,
        CategoriesId.MONITOR_STAND to R.drawable.ic_stand,
        CategoriesId.POWER_PRODUCTS to R.drawable.ic_power_supply,
        CategoriesId.POWER_SUPPLY to R.drawable.ic_power_supply,
        CategoriesId.FLASH_DRIVES to R.drawable.ic_memory,
        CategoriesId.MOUSE to R.drawable.ic_mouse,
        CategoriesId.KEYBOARD to R.drawable.ic_keyboard,
        CategoriesId.MOTHERBOARD to R.drawable.ic_motherboard,
        CategoriesId.PAD_MOUSE to R.drawable.ic_mousepad,
        CategoriesId.TABLET_AND_MOBILES to R.drawable.ic_mobile,
        CategoriesId.MONITORS to R.drawable.ic_monitor,
    )
}